# Generated by Django 5.1.5 on 2025-06-19 10:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PongPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(blank=True, max_length=30, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
            ],
        ),
        migrations.CreateModel(
            name='GameSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_speed', models.CharField(choices=[('slow', 'Slow'), ('normal', 'Normal'), ('fast', 'Fast')], default='normal', max_length=10)),
                ('ball_size', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='medium', max_length=10)),
                ('paddle_size', models.CharField(choices=[('short', 'Short'), ('normal', 'Normal'), ('long', 'Long')], default='normal', max_length=10)),
                ('power_jump', models.CharField(choices=[('on', 'On'), ('off', 'Off')], default='on', max_length=10)),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='light', max_length=10)),
                ('font_size', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='medium', max_length=10)),
                ('language', models.CharField(choices=[('eng', 'English'), ('fin', 'Finnish'), ('swd', 'Swedish')], default='eng', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PongSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_player_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_player_1', to='pong.pongplayer')),
                ('active_player_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_player_2', to='pong.pongplayer')),
                ('active_player_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_player_3', to='pong.pongplayer')),
                ('active_player_4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_player_4', to='pong.pongplayer')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='pongplayer',
            name='player_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pong.pongsession'),
        ),
        migrations.CreateModel(
            name='PongGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_type', models.CharField(max_length=4)),
                ('game_score', models.CharField(blank=True, null=True)),
                ('game_loser_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_loser_1', to='pong.pongplayer')),
                ('game_loser_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_loser_2', to='pong.pongplayer')),
                ('game_winner_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_winner_1', to='pong.pongplayer')),
                ('game_winner_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_winner_2', to='pong.pongplayer')),
                ('game_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pong.pongsession')),
            ],
        ),
        migrations.CreateModel(
            name='PongTournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament_type', models.CharField(max_length=4)),
                ('semi_one_p1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semi_one_p1', to='pong.pongplayer')),
                ('semi_one_p2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semi_one_p2', to='pong.pongplayer')),
                ('semi_two_p1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semi_two_p1', to='pong.pongplayer')),
                ('semi_two_p2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semi_two_p2', to='pong.pongplayer')),
                ('tournament_game_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tournament_game_1', to='pong.ponggame')),
                ('tournament_game_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tournament_game_2', to='pong.ponggame')),
                ('tournament_game_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tournament_game_3', to='pong.ponggame')),
                ('tournament_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pong.pongsession')),
            ],
        ),
        migrations.AddConstraint(
            model_name='pongplayer',
            constraint=models.UniqueConstraint(fields=('player_session', 'player_name'), name='Unique player names for each session'),
        ),
    ]
