# Generated by Django 5.1.5 on 2025-06-26 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0002_auto_20250625_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesettings',
            name='custom_media_root',
            field=models.CharField(blank=True, help_text='Custom media root path (optional)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='gamesettings',
            name='custom_media_url',
            field=models.CharField(blank=True, help_text='Custom media URL (optional)', max_length=255, null=True),
        ),
    ]
