# Generated by Django 5.1.5 on 2025-06-27 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0003_gamesettings_custom_media_root_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pongplayer',
            name='avatar',
            field=models.ImageField(blank=True, default='/media/avatars/default-avatar.png', null=True, upload_to='avatars/'),
        ),
    ]
