# Generated by Django 5.1.5 on 2025-07-03 09:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0004_alter_pongplayer_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='ponggame',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 7, 3, 0, 0, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
